### PR TITLE
Use .vue file for DraggableHeader component

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
@Zaid-Ajaj I was checking in the compiler what was the best way to re-enable the `ExportDefault` attribute, but then I realize we can just use `Emit` 😅 so I've added the following helper for now directly here:

```fsharp
[<Emit("export default $0")>]
let exportDefault (x: obj): unit = jsNative
```

And [with this](https://github.com/alfonsogarciacaro/fable-vue/compare/export-default?expand=1#diff-5955966180c9e73da1ffaee2502eaac9R75) we can make the component compatible with .vue files :tada: It was easier than I thought. The only inconvenience is you need to use the string path to [import the component](https://github.com/alfonsogarciacaro/fable-vue/compare/export-default?expand=1#diff-e8d10de982686f75033e0c1dd2b4806fR9). But you get HMR support which is quite cool 😸

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
@Zaid-Ajaj @Lanayx I've been experimenting with the API and added some magic to the latest fable-compiler-dotnet release (please run `npm i` again before testing) to make the component declaration more succint (check how DraggableHeader and App are declared now at the bottom of the files).

One of the enhancements is allowing direct .fs file references without referencing the .fsproj first. If you check the latest code in the PR, the entry file called by Webpack is now `src/index.js`. This is not necessary if you have a full F# project, but it should be helpful for people that would like to introduce Fable into an existing project.

**Comment by Lanayx** [comment]
These enhancements look nice for me =)

**Comment by Zaid-Ajaj** [comment]
Using the `src/index.js` as an entry is the best thing ever :heart: although I am not a big fan of `nameof2` because it is too specific for this use-case, doesn't it work as is if you did the following?
```fs
Vue.computed (nameof contentPosition) contentPosition 
```

**Comment by alfonsogarciacaro** [comment]
But, but `nameof2` is clearly much better than `nameof` because it has a 2 in the name!

Actually I started with `Vue.computed (nameof contentPosition) contentPosition` but didn't like the repetition. I just turned the arguments into a tuple, you can still use custom names `Vue.computed ("foo", fun _ -> 5)`. If you prefer to keep the curried arguments, we can do something like `nameof2 contentPosition ||> Vue.component`.

**Comment by alfonsogarciacaro** [comment]
Anyways, I'm going to merge this, stand back!

**Pull request merged**
